apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
  namespace: broker
data:
  DATABOLT_SHARED_DIR: "/home/databolt"
  TTN_FORMATTER_SRC_PATH: "/home/ttn-formatters"
  PGHOST: "db"
  PGPORT: "5432"
  PGUSER: "postgres"
  PGPASSWORD: "CHANGEME"
  PGDATABASE: "broker"
  POSTGRES_PASSWORD: "CHANGEME"
  POSTGRES_DB: "broker"
  DB_INIT: "/home/broker/db/init.d"
  PYTHONPATH: "/home/broker/python"
  TTN_API_TOKEN: "Bearer abc"
  UBIDOTS_API_TOKEN: "x"
  RABBITMQ_HOST: "mq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_DEFAULT_USER: "broker"
  RABBITMQ_DEFAULT_PASS: "CHANGEME"
  RABBITMQ_CONFIG_PATH: "/home/broker/config/rabbitmq"
  WEBSITE_PATH: "/home/broker/src/www"
  GREENBRAIN_USERS: "abc@abc.com,xyz@xyz.com"
  GREENBRAIN_PASSWORDS: "pwd1,pwd2"
  TZ: "Australia/Sydney"
  PYTHON_SRC_PATH: "/home/broker/src/python"
  TTN_DECODER_SRC_PATH: "/home/broker/src/js/ttn_decoder/src"
  EAGLEIO_API_TOKEN: "abc1"
