apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq
  template:
    metadata:
      labels:
        app: mq
    spec:
      containers:
        - name: mq
          image: rabbitmq:3.9-management
          envFrom:
            - configMapRef:
                name: env-configmap
          #readinessProbe:
          #  exec:
          #    command:
          #      - rabbitmq-diagnostics
          #      - check_port_connectivity
          #  initialDelaySeconds: 30
          #  periodSeconds: 30
          ports:
            - containerPort: 5672
            - containerPort: 15672
            - containerPort: 1883
            - containerPort: 15692
          volumeMounts:
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq/mnesia/rabbit@mq
      volumes:
        - name: rabbitmq-config
          hostPath:
            path: /opt/broker/config/rabbitmq
        - name: rabbitmq-data
          hostPath:
            path: /opt/broker_data/rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: mq
spec:
  type: NodePort
  selector:
    app: mq
  ports:
    - name: amqp
      port: 5672
      #nodePort: 30000
    - name: management
      port: 15672
      #nodePort: 30000
    - name: mqtt
      port: 1883
      #nodePort: 30000
    - name: prometheus
      port: 15692
      #nodePort: 30000
