apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
  namespace: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
        - name: restapi
          image: broker/python-base:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env-configmap
          workingDir: /home/broker/python/restapi
          command:
            - /home/broker/.local/bin/uvicorn
          args:
            - --proxy-headers
            - --host
            - 0.0.0.0
            - --port
            - "5687"
            - RestAPI:app
          livenessProbe:
            httpGet:
              path: /openapi.json
              port: 5687
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /openapi.json
              port: 5687
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          ports:
            - containerPort: 5687
          volumeMounts:
            - name: shared-data
              mountPath: /home/broker/python
      volumes:
        - name: shared-data
          hostPath:
            path: /opt/broker/src/python
---
apiVersion: v1
kind: Service
metadata:
  name: restapi
  namespace: broker
spec:
  type: NodePort
  selector:
    app: restapi
  ports:
    - name: http
      port: 5687
      #nodePort: 30000
