apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttn-webhook
  namespace: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttn-webhook
  template:
    metadata:
      labels:
        app: ttn-webhook
    spec:
      containers:
        - name: ttn-webhook
          image: broker/python-base
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env-configmap
          workingDir: /home/broker/python/ttn
          command:
            - /home/broker/.local/bin/uvicorn
            - --proxy-headers
            - --host
            - 0.0.0.0
            - --port
            - "5688"
            - WebHook:app
          ports:
            - containerPort: 5688
          volumeMounts:
            - name: shared-data
              mountPath: /home/broker/python
      volumes:
        - name: shared-data
          hostPath:
            path: /opt/broker/src/python
---
apiVersion: v1
kind: Service
metadata:
  name: ttn-webhook
  namespace: broker
spec:
  selector:
    app: ttn-webhook
  ports:
    - name: http
      port: 5688
