apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttn-decoder
  namespace: broker
spec:
  selector:
    matchLabels:
      app: ttn-decoder
  replicas: 1
  template:
    metadata:
      labels:
        app: ttn-decoder
    spec:
      containers:
        - name: ttn-decoder
          image: broker/ttn_decoder
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env-configmap
          workingDir: "/usr/src/ttn_decoder"
          command:
            - node
            - src
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: ttn-decoder-volume
              mountPath: /usr/src/ttn_decoder/src
            - name: ttn-formatters-volume
              mountPath: /usr/src/ttn_formatters
      volumes:
        - name: ttn-decoder-volume
          hostPath:
            path: /opt/broker/src/js/ttn_decoder/src
        - name: ttn-formatters-volume
          hostPath:
            path: /opt/ttn-formatters
---
apiVersion: v1
kind: Service
metadata:
  name: ttn-decoder
  namespace: broker
spec:
  selector:
    app: ttn-decoder
  ports:
    - name: http
      port: 3001
      #nodePort: 30000
